# Generated by Django 4.1.2 on 2022-11-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cod', models.CharField(max_length=15)),
                ('disciplinas', models.ManyToManyField(related_name='disciplina', to='disciplina.disciplina')),
            ],
        ),
    ]
